# Generated by Django 2.1.5 on 2019-05-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
