# Generated by Django 2.1.5 on 2019-05-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190526_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
