# Generated by Django 2.1.5 on 2019-05-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190528_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
