# Generated by Django 2.1.5 on 2019-05-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20190528_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_no',
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
